language: ruby
cache: bundler
addons:
  postgresql: "9.4"
before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
 - bundle exec rake db:setup
rvm:
 - 2.4.1
env:
 - CI=true
script:
 - bundle exec brakeman
 - bundle exec i18n-tasks health
 - bundle exec rubocop -c .rubocop.yml
 - bundle exec rspec
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
