payments:
  currency: EUR
  fractions_per_unit: 100
  allow_reprocess_hours: 120
  orders_batch_processing_errors_limit: 3
  default_processors:
    credit_card: redsys
    direct_debit: sepa
  processors:
    redsys:
      notification_lifespan: 30 #minutes
      auth:
        name: <%= ENV["REDSYS_NAME"] %>
        login: <%= ENV["REDSYS_MERCHANT_ID"] %>
        secret_key: <%= ENV["REDSYS_SECRET_KEY"] %>
        terminal: <%= ENV["REDSYS_TERMINAL"] %>
        test: <%= Rails.env.test? || Rails.env.development? %>
      response_codes:
        ok:
          flags:
            - verified
          codes: ["0000", "0001", "0002", "0003", "0004", "0005", "0006", "0007", "0008", "0009", "0010", "0011", "0012", "0013", "0014", "0015", "0016", "0017", "0018", "0019", "0020", "0021", "0022", "0023", "0024", "0025", "0026", "0027", "0028", "0029", "0030", "0031", "0032", "0033", "0034", "0035", "0036", "0037", "0038", "0039", "0040", "0041", "0042", "0043", "0044", "0045", "0046", "0047", "0048", "0049", "0050", "0051", "0052", "0053", "0054", "0055", "0056", "0057", "0058", "0059", "0060", "0061", "0062", "0063", "0064", "0065", "0066", "0067", "0068", "0069", "0070", "0071", "0072", "0073", "0074", "0075", "0076", "0077", "0078", "0079", "0080", "0081", "0082", "0083", "0084", "0085", "0086", "0087", "0088", "0089", "0090", "0091", "0092", "0093", "0094", "0095", "0096", "0097", "0098", "0099", "0400", "0481", "0500", "0900"]
        no_credit:
          role: user
          codes: ["0116", "0181", "0182", "0190", "0290", "9261"]
        expired:
          role: user
          flags:
            - inactive
          codes: ["0101", "0201"]
        wrong_data:
          role: user
          flags:
            - inactive
          codes: ["0118", "0125", "0129", "0180", "0184", 0191", "0280", "9064", "9093"]
        fraud:
          role: finances
          codes: ["0102", "0107", "0167", "0202", "0207", "0208", "0209"]
    sepa:
      main:
        name: <%= ENV["SEPA_NAME"] %> # Name of the initiating party and creditor (max. 70 chars)
        iban: <%= ENV["SEPA_IBAN"] %> # International Bank Account Number of the creditor (max. 34 chars)
        bic: <%= ENV["SEPA_BIC"] %> # International Bank Account Number of the creditor (8 or 11 chars)
        creditor_identifier: <%= ENV["SEPA_CREDITOR_IDENTIFIER"] %> # Creditor Identifier (max. 35 chars)
      file_lifespan: 48 #hours
      response_codes:
        ok:
          flags:
            - verified
          codes:
            - OK

people:
  document_id_minimum_length: 4
  external_systems:
    - decidim

procedures:
  auto_processables:
    - cancellation
    - membership_level_change
    - person_data_change
    - registration
  undo_minutes: 30
  untrusted_email:
    domains_blacklist:
      - mailinator.com
  untrusted_phone:
    phones_blacklist:
      - "0012026601367"
    prefixes_blacklist:
      - "0034602"

regional:
  local_code: ES
  locales:
    default: es
    available: # don't include default locale
      - ca
      - eu
      - en
      - gl

security:
  allowed_ips:
    api_clients: <%= ENV.fetch("ALLOWED_IPS_API_CLIENTS") { "" } &.split(/[^\.\d]/) %>
    payment_callbacks: <%= ENV.fetch("ALLOWED_IPS_CALLBACK_PAYMENTS") { "" } &.split(/[^\.\d]/) %>
  request_rate_limit: 300
  host_url: <%= ENV["HOST_URL"] %>
