
default: &default
  username: <%= ENV.fetch("SNEAKERS_USERNAME") { "jobs" } %>
  password: <%= ENV.fetch("SNEAKERS_PASSWORD") { "jobs" } %>
  host: <%= ENV.fetch("SNEAKERS_HOST") { "localhost" } %>
  port: <%= ENV.fetch("SNEAKERS_PORT") { 5672 } %>
  vhost: <%= ENV.fetch("SNEAKERS_VHOST") { "/jobs" } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV["SNEAKERS_URL"] %>
