#
# Symmetric Encryption for Ruby
#
---
simple: &simple
  key: 1234567890ABCDEF
  iv: 1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding: :base64strict
  always_add_header: true

file_based: &file_based
  private_rsa_key: "<%= ENV.fetch("ATTACHMENTS_KEY", "").gsub("\n","\\n") %>"

cipher: &cipher
  cipher_name:       aes-256-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  <<: *simple

development: 
  <<: *file_based
  ciphers:
    -
      <<: *cipher
      key_filename: /etc/census/keys/development.key
      iv_filename: /etc/census/keys/development.iv
      version: 1

production:
  <<: *file_based
  ciphers:
    -
      <<: *cipher
      key_filename: /etc/census/keys/production.key
      iv_filename: /etc/census/keys/production.iv
      version: 1

# uncomment this to generate keys for development environment
#development:
#  <<: *simple
